export const PATH = {
  auth: {
    login: '/auth/login',
  },
  component: '/component',
  notFound: '/404',
  home: '/app/home',
  comics: {
    root: '/app/comics',
    list: '/app/comics/list',
    new: '/app/comics/new',
    detail: '/app/comics/detail/:id',
    edit: '/app/comics/edit/:id',
  },
  chapters: {
    root: '/app/chapters',
    list: '/app/chapters/list',
    new: '/app/chapters/new',
    detail: '/app/chapters/detail/:id',
    edit: '/app/chapters/edit/:id',
  },
  novel: '/app/novel',
  translator: '/app/translator',
  user: '/app/user',
  author: '/app/author',
  genres: '/app/genres',
  comments: '/app/comments',
  settings: '/app/settings',
  logout: '/app/logout',
  docs: '/app/docs',
  profile: '/app/profile',
};
