export const fullName = [
  'Sandra Trevino',
  'Angela Morrison',
  'Aubrey Short',
  'Kali Davies',
  'Agustin Obrien',
  'Adelaide Spencer',
  'Blaze Kirk',
  'Benjamin Hopkins',
  'Lillie Burnett',
  'Ali Rasmussen',
  'Teagan Perkins',
  'Janessa Gilmore',
  'Greta Fry',
  'Nolan Stone',
  'Heath Thompson',
  'Patricia Mcdaniel',
  'Alfredo Maxwell',
  'Gerardo Kaufman',
  'Gracie Barber',
  'Marshall Williamson',
  'Caiden Marquez',
  'Nico Barton',
  'Jean Olsen',
  'Micheal Wells',
  'Bobby Bell',
  'Madalynn Norris',
  'Maliyah Wade',
  'Annalise Baird',
  'Makenna Zimmerman',
  'Evie Quinn',
  'Zander Thornton',
  'Denisse Barr',
  'Emery Washington',
  'Fabian Collins',
  'Donavan Clayton',
  'Gaige Peters',
  'Cristina Terry',
  'Jaliyah Giles',
  'Darren Sosa',
  'Savion Hardin',
  'Jackson Johnston',
  'Donald Lucas',
  'Carlos Norris',
  'Aryana French',
  'Ruben Winters',
  'Mohamed Cabrera',
  'Tamia Chase',
  'Frank Cowan',
  'Julia Hanna',
  'Bennett Franco',
];

export const things = [
  'card',
  'balloon',
  'teddies',
  'cup',
  'bottle cap',
  'bowl',
  'door',
  'doll',
  'speakers',
  'sandal',
  'sticky note',
  'model car',
  'hanger',
  'clothes',
  'perfume',
  'keyboard',
  'toothbrush',
  'bed',
  'mirror',
  'shampoo',
  'television',
  'tree',
  'ring',
  'sand paper',
  'paint brush',
  'paper',
  'soy sauce packet',
  'air freshener',
  'car',
  'sponge',
  'tomato',
  'sharpie',
  'stop sign',
  'toilet',
  'toothpaste',
  'lamp',
  'spoon',
  'fridge',
  'headphones',
  'nail clippers',
  'cork',
  'brocolli',
  'lotion',
  'shovel',
  'candy wrapper',
  'buckle',
  'keys',
  'USB drive',
  'white out',
];

export const firstName = [
  'Mossie',
  'David',
  'Ebba',
  'Chester',
  'Eula',
  'Jaren',
  'Boyd',
  'Brady',
  'Aida',
  'Anastasia',
  'Gregoria',
  'Julianne',
  'Ila',
  'Elyssa',
  'Lucio',
  'Lewis',
  'Jacinthe',
  'Molly',
  'Brown',
  'Fritz',
  'Keon',
  'Ella',
  'Ken',
  'Whitney',
  'Monte',
  'Rose',
  'Shana',
  'Devon',
  'Jaleel',
  'Laury',
  'Brooks',
  'Bruce',
  'Avery',
  'Esperanza',
  'Helene',
  'Heloise',
  'Elinor',
  'Adeline',
  'Haley',
  'Anabelle',
];

export const lastName = [
  'Carroll',
  'Simonis',
  'Yost',
  'Hand',
  'Emmerich',
  'Wilderman',
  'Howell',
  'Sporer',
  'Boehm',
  'Morar',
  'Koch',
  'Reynolds',
  'Padberg',
  'Watsica',
  'Upton',
  'Yundt',
  'Pfeffer',
  'Parker',
  'Zulauf',
  'Treutel',
  'McDermott',
  'McDermott',
  'Cruickshank',
  'Parisian',
  'Auer',
  'Turner',
  'Dooley',
  'Wiegand',
  'Abbott',
  'Wisoky',
  'Fahey',
  'Satterfield',
  'Bahringer',
  'Schulist',
  'Durgan',
  'Carroll',
  'Jones',
  'Leffler',
  'Gutkowski',
  'Homenick',
];
